name: ionic build
on: 
  push:
    branches:
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'zulu'
      - name: setup android
        uses: android-actions/setup-android@v2
      - name: build
        run: |
          npm install -g @ionic/cli
          npm install
          ionic capacitor build android
      
      
      
