name: ionic build
on: 
  push:
    branches:
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.18+10
          distribution: 'temurin'
      - name: setup android
        uses: android-actions/setup-android@v2
      - uses: actions/checkout@main
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleRelease
      - name: build
        run: |
          npm install -g @ionic/cli
          sudo npm install
          ionic capacitor build android
      
      
      
