name: ionic build
on: 
  push:
    branches:
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      uses: actions/setup-java@v3
        with:
          java-version: 1.8
      uses: android-actions/setup-android@v2
      run: |
        npm install -g @ionic/cli
        npm install
        ionic capacitor build android
      
      
      
